// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Arc1;
void ui_event_Label7(lv_event_t * e);
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui____initial_actions0;
extern lv_obj_t * label1;
extern lv_obj_t * label2;
extern lv_obj_t * label3;
extern lv_obj_t * label4;

void ui_init(void);
static void btn_event_cb(lv_event_t * e);
static void slider_event_cb(lv_event_t * e);
static void arc_event_cb(lv_event_t * e);
static void ui_Switch1_event_cb(lv_event_t * e);
static void ui_Switch2_event_cb(lv_event_t * e);
static void btn_event_handler(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
